AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  reciprocity-drops

Parameters:
  SlackSigningSecret:
    Type: String
    Default: undefined

Resources:
  SlackHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: handlers/slack
      Timeout: 3
      Events:
        SlackRequest:
          Type: Api
          Properties:
            Method: post
            Path: /slack/data
            RestApiId: !Ref Api
      Layers:
        - !Ref SlackUtilsLayer
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
  SlackUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: slackutils
      Description: Utilities for slack related functions
      ContentUri: layers/slackUtils
      CompatibleRuntimes:
        - nodejs20.x
    Metadata:
      BuildMethod: makefile
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: Slack gateway
      StageName: api
