AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  reciprocity-drops

Parameters:
  SlackSigningSecret:
    Type: String
    Default: undefined
  APITOKEN:
    Type: String
    Default: undefined

Resources:
  ### Lambda Functions
  SlackHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: handlers/slack
      Timeout: 3
      Events:
        SlackRequest:
          Type: Api
          Properties:
            Method: post
            Path: /slack/data
            RestApiId: !Ref Api
      Layers:
        - !Ref SlackUtilsLayer
      Environment:
        Variables:
          EXPORTQUEUE_URL: !Ref ExportDataQueue
          SLACK_SIGNING_SECRET: !Ref SlackSigningSecret
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt ExportDataQueue.QueueName

  ExportDataHandler:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: handlers/ExportData
      Timeout: 25
      Events:
        ExportDataRequest:
          Type: SQS
          Properties:
            Queue: !GetAtt ExportDataQueue.Arn
      Layers:
        - !Ref SlackUtilsLayer
      Environment:
        Variables:
          API_TOKEN: !Ref APITOKEN

  ### Lambda Layers
  SlackUtilsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: slackutils
      Description: Utilities for slack related functions
      ContentUri: layers/slackUtils
      CompatibleRuntimes:
        - nodejs20.x
    Metadata:
      BuildMethod: makefile

  ### SQS Queues
  ExportDataQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ExportDataQueue

  ### APIs
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: Slack gateway
      StageName: api
