name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Setup AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build and deploy
        env:
          SlackSigningSecret: ${{ secrets.SLACK_SIGNING_SECRET }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          sam build
          sam deploy --stack-name ReciprocityDrops --region ca-central-1 --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --parameter-overrides "SlackSigningSecret=$SlackSigningSecret" "API_TOKEN=$API_TOKEN"

      - shell: bash
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-Type: application/json' $WEBHOOK_URL --data '{"content":"@here Deploy AWS SAM - ${{ github.event.repository.name }} to PROD Complete"}'
